// Mocks generated by Mockito 5.4.5 from annotations
// in game_deal/test/saved_deals_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:game_deal/models/deal.dart' as _i4;
import 'package:game_deal/services/storage_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i2.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> initHive() => (super.noSuchMethod(
        Invocation.method(
          #initHive,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveDeal(_i4.Deal? deal) => (super.noSuchMethod(
        Invocation.method(
          #saveDeal,
          [deal],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> removeDeal(String? dealId) => (super.noSuchMethod(
        Invocation.method(
          #removeDeal,
          [dealId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  List<_i4.Deal> getSavedDeals() => (super.noSuchMethod(
        Invocation.method(
          #getSavedDeals,
          [],
        ),
        returnValue: <_i4.Deal>[],
      ) as List<_i4.Deal>);

  @override
  bool isDealSaved(String? dealId) => (super.noSuchMethod(
        Invocation.method(
          #isDealSaved,
          [dealId],
        ),
        returnValue: false,
      ) as bool);
}
